### ISSUE TITLE
Support custom themes

### ISSUE THREAD

**Issue by slowli** [slowli/term-transcript#14]
Low-priority for now, but the crate features necessary foundation; rendering is performed via Handlebars, so the template can be customized in runtime.

**Comment by antenore** [comment]
First of, this is a great project!!!

I'm very interested in this functionality, can I be of any support? In terms of programming I'm a total n00b in rust, but maybe I can sponsor the development?

I hope everything is fine for you where you live :-\

**Comment by slowli** [comment]
Hi! Glad that this project is helpful for you. Just to understand better: Are you interested in custom template support specifically? If so, would it be ideal to add it to CLI, or is there another way it can be deployed? (This would most probably imply adding the relevant functionality to the library crate as well - CLI is just another library user.)

In general, the roadmap to support custom templates is pretty clear, and this doesn't seem that large of a task. The library is *sort of* built to support template customization, since the rendering logic is already implemented using a [Handlebars](https://handlebarsjs.com/) [template](https://github.com/slowli/term-transcript/blob/4806810309d4256df13e17b36d7424b97c76b247/src/svg/default.svg.handlebars). The bulk of work would be to tidy up and document variables provided to a template and expectations from the template (e.g., classes used to apply text styling). If you don't mind some wait (a couple of weeks or so), I can take this task for myself.

> I hope everything is fine for you where you live :-\

Thanks for the concern, it's fine as it can be.

**Comment by slowli** [comment]
@antenore FYI, I've started implemented this functionality in #35. If you could take a look and share feedback, that would be awesome! Here's a rough guide to the changes:

- The (slightly reworked) default Handlebars template is [here](https://github.com/slowli/term-transcript/blob/93108bffb9187baae2ba86ca86e15ad84a970e93/src/svg/default.svg.handlebars).
- Documentation for available Handlebars helpers is [here](https://github.com/slowli/term-transcript/blob/93108bffb9187baae2ba86ca86e15ad84a970e93/src/svg/mod.rs#L158). (It will be available in more human-readable form [here](https://slowli.github.io/term-transcript/term_transcript/svg/struct.Template.html) after #35 is merged.)
- Data available for templates is documented [here](https://github.com/slowli/term-transcript/blob/93108bffb9187baae2ba86ca86e15ad84a970e93/src/svg/data.rs) (again, it would be more readable after the merge).
- An example of an alternative HTML template is [here](https://github.com/slowli/term-transcript/blob/93108bffb9187baae2ba86ca86e15ad84a970e93/examples/custom.html.handlebars), together with [an example of generated output](https://github.com/slowli/term-transcript/blob/93108bffb9187baae2ba86ca86e15ad84a970e93/examples/rainbow.html).

You can install the CLI even before the merge using [`cargo install`](https://doc.rust-lang.org/cargo/commands/cargo-install.html) with `--git` and `--rev` options specified.

**Comment by antenore** [comment]
Awesome! Thank you! I'll test ASAP

**Comment by slowli** [comment]
@antenore Did you have a chance to look at the changes? Any kind of feedback would be greatly appreciated.
