### ISSUE TITLE
FR: Custom width for the window

### ISSUE THREAD

**Issue by ilyagr** [slowli/term-transcript#59]
Currently, the width of the "terminal" seems to be fixed at 80 characters. I wonder if it could be adjustable, so that I don't get extraneous wrapping.

**Comment by ilyagr** [comment]
Some notes-to-self:

The library version of `term-transcript` does support an arbitrary width, but the user seems to need to *also* specify the width of the SVG in other units, guessing at the width of each characters (which in practice seems to be 9 SVG units).

**Comment by slowli** [comment]
You're right in that the width in chars and the window width are two different parameters, related to each other. The relation is not quite straightforward; it depends on the font used and on the rendering engine. It's straightforward to add both width params to CLI (and maybe the height in lines as well); I'll do this in near future.

**Comment by ilyagr** [comment]
Thank you!
